In [1]:
import pandas as pd
import openpyxl
import win32com.client

In [7]:
# template_name='automated_loss_ratio_report_template.xlsx'
# report_name='{group_name} - care range gap cover - {year} claims experience.pdf'.format(group_name=group_name,year=year)
file_name='HighGpClaim.csv'
file_path='C:\\Users\\christo.strydom\\github_repos\\fraud_project\\data\\'
file=file_path+file_name

In [8]:
df=pd.read_csv(filepath_or_buffer=file)

In [9]:
list(df)

['Scheme_Option_No',
 'Medstar_No',
 'Medstar_Dependant_No',
 'Active_Flag',
 'Benefit_Start_Date',
 'Scheme_Option_Desc',
 'Medical_Aid_No',
 'Scheme_Dependant_No',
 'Scheme_Start_Date',
 'Scheme_End_Date',
 'Changed_Date',
 'MainMemberName',
 'MainMemberSurname',
 'Main_Member_Homephone',
 'ManinMemberIDNo',
 'Main_Member_Email',
 'Main_Member_Cellphone',
 'mainmemberGender',
 'Dependant_First_Name',
 'Dependant_Surname',
 'Dependant_Birth_Date',
 'Dependant_Join_Date',
 'Dependant_Benefit_Start_Date',
 'Dependant_Member_Email',
 'comp_code',
 'name',
 'Aug_out_cons',
 'Sep_out_cons',
 'Oct_out_cons',
 'Nov_out_cons',
 'Dec_out_cons',
 'Jan_out_cons',
 'Feb_Out_Cons',
 'Mar_Out_Cons',
 'Apr_Out_Cons',
 'May_Out_Cons',
 'Jun_Out_Cons',
 'Jul_Out_Cons',
 'Registered for Chronic',
 'Chronic Condition',
 'Count_OF_GP_Visited',
 'Claimed_Amount',
 'Benefit_Amount',
 'Total_Consults',
 'ICDDescription',
 'DoctorNumber']

In [ ]:
# template_name='automated_loss_ratio_report_template.xlsx'
# report_name='{group_name} - care range gap cover - {year} claims experience.pdf'.format(group_name=group_name,year=year)
file_name='claims_history_with_Dr_details.csv'
file_path='C:\\Users\\christo.strydom\\github_repos\\fraud_project\\data\\'
file=file_path+file_name

In [ ]:
claims_history_with_Dr_details_df=pd.read_csv(filepath_or_buffer=file)

In [ ]:
claims_history_with_Dr_details_df.shape

In [ ]:
claims_history_with_Dr_details_df['SchemeCode'].value_counts()

In [ ]:
list(claims_history_with_Dr_details_df)

In [ ]:
pd.read_csv(filepath_or_buffer=file,encoding = "ISO-8859-1")

In [ ]:
# template_name='automated_loss_ratio_report_template.xlsx'
# report_name='{group_name} - care range gap cover - {year} claims experience.pdf'.format(group_name=group_name,year=year)
file_name='claims_history_with_Dr_details.csv'
file_path='C:\\Users\\christo.strydom\\github_repos\\fraud_project\\data\\'
file=file_path+file_name
df=pd.read_csv(filepath_or_buffer=file)

In [ ]:
list(df)

In [ ]:
df['ClaimAuthDate']

In [ ]:
df[~df['AdmissionDate'].isna()]

In [ ]:
df[['ClaimCaptureDate',
 'ClaimProcessDate',
 'ClaimAuthDate',
 'ClaimPayDate','AdmissionDate']]

In [ ]:
df['ClaimCaptureDatePy']=pd.to_datetime(df['ClaimCaptureDate'])
df['ClaimProcessDatePy']=pd.to_datetime(df['ClaimProcessDate'])
df['ClaimPayDatePy']=pd.to_datetime(df['ClaimPayDate'])
df['AdmissionDatePy']=pd.to_datetime(df['AdmissionDate'])
# df['ClaimCaptureDatePy']=pd.to_datetime(df['ClaimCaptureDate'])

In [ ]:
df['duration']=(df['ClaimCaptureDatePy']-df['AdmissionDatePy']).dt.days

In [ ]:
df['duration'].value_counts()

In [ ]:
df['ClaimCaptureDatePy'].value_counts()

In [ ]:
list(set(df['ClaimCaptureDate']))

In [ ]:
doctor_name_list=list(set(df['doctor_name']))

In [ ]:
doctor_name_list

In [ ]:
# [a for a in doctor_name_list if '' in a.upper()]

In [ ]:
set(df['RejectionReason'])

In [ ]:
set(df['DiagnosisCategory'])

In [ ]:
set(df['PatientRelationship'])

In [ ]:
len(set(df.PracticeNr))

In [ ]:
len(set(df.PolicyNumber))

In [ ]:
len(set(df.DiagnosisCategory))

In [ ]:
df[~df['IdNumber'].isna()]

In [ ]:
set(df['PatientIDnr'])

In [ ]:
len(set(df[~df['PatientIDnr'].isna()]['PatientIDnr']))

### datafile: data-1610005188424

In [10]:
# template_name='automated_loss_ratio_report_template.xlsx'
# report_name='{group_name} - care range gap cover - {year} claims experience.pdf'.format(group_name=group_name,year=year)
file_name='data-1610005188424.csv'
file_path='C:\\Users\\christo.strydom\\github_repos\\fraud_project\\data\\'
file=file_path+file_name
df=pd.read_csv(filepath_or_buffer=file)

In [11]:
list(df)

['scheme_fk',
 'scheme_name',
 'ms_fk',
 'dependent_no',
 'dep_type',
 'gender',
 'first_name',
 'surname',
 'birth_date',
 'claim_fk',
 'claim_date',
 'practice_no',
 'doctor_name',
 'pr_type',
 'pr_type_descr',
 'pr_group_descr',
 'tariff_fk',
 'claim_type',
 'claim_code',
 'claim_code_description',
 'icd10_fk',
 'icd10_descr',
 'icd10_group_description',
 'auth_fk',
 'units',
 'pmb',
 'in_hospital_indicator',
 'claimed_amount',
 'benefit_amount',
 'ClaimsStatus',
 'rcvd_date',
 'assess_date',
 'paid_date',
 'tariff_amount',
 'discount',
 'owes',
 'override',
 'gen_no',
 'suspend_until',
 'suspended',
 'assessed_datetime']

In [12]:
df['ClaimsStatus']

0          Pending
1          Pending
2         Rejected
3          Pending
4         Rejected
            ...
634782        Paid
634783        Paid
634784        Paid
634785        Paid
634786        Paid
Name: ClaimsStatus, Length: 634787, dtype: object

In [6]:
df[['scheme_fk',
 'scheme_name']]

        scheme_fk                    scheme_name
0             108     KAELO HEALTH MYHEALTH PLUS
1             108     KAELO HEALTH MYHEALTH PLUS
2             128                 FLEXICARE PLUS
3             108     KAELO HEALTH MYHEALTH PLUS
4             128                 FLEXICARE PLUS
...           ...                            ...
634782        129  KAELO HEALTH MYHEALTH PLUS SI
634783        108     KAELO HEALTH MYHEALTH PLUS
634784        108     KAELO HEALTH MYHEALTH PLUS
634785        124    KAELO HEALTH MYHEALTH VITAL
634786        108     KAELO HEALTH MYHEALTH PLUS

[634787 rows x 2 columns]

In [5]:
df['ms_fk']

0         1491980
1          504489
2         6013410
3          508627
4         6022125
           ...
634782    1508108
634783    1643150
634784    1643150
634785    1505469
634786    1643150
Name: ms_fk, Length: 634787, dtype: int64

In [43]:
def isOneToOne(df, col1, col2):
    first = df.groupby(col1)[col2].count().max()
    second = df.groupby(col2)[col1].count().max()
    return first + second == 2

In [44]:
isOneToOne(df,'practice_no','doctor_name')

False

In [46]:
df.groupby(['practice_no', 'doctor_name'])\
  .apply(lambda x : x.count())\
  .iloc[:,0]\
  .unstack()\
  .fillna(0)

doctor_name,4EYES OPTOMETRIST,50 SHADES OPTOMETRIST,A K AMOD INC,A MAHOMED OPTOMETRIST,A MOODLEY OPTOMETRIST,A MOUTON DR,A PARKER OPTOMETRISTS,A. SARWAR OPTOMETRIST,A.G.M. MAYAT OPTOMETRISTS,A.R. HASSIM OPTOMETRIST,...,ZULU MB DR,ZULU NA DR,ZULU SN DR,ZUNGU EM DR,"de Beer E, Mrs","de Jager Christo J, Dr","de Klerk M J, Dr","le Roux J J, Dr","van der Lingen J S H, Dr","van der Merwe H J, Dr"
practice_no,,,,,,,,,,,,,,,,,,,,,
566,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
825,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1651,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1708,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1724,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999142,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9999145,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9999146,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9999147,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9999148,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
df['ms_fk_id']=df['ms_fk'].astype(str)+'_'+df['dependent_no'].astype(str).apply(lambda x: x.zfill(2))

In [26]:
df['dependent_no'].astype(str).apply(lambda x: x.zfill(2))

0         00
1         01
2         00
3         00
4         02
          ..
634782    00
634783    00
634784    00
634785    01
634786    00
Name: dependent_no, Length: 634787, dtype: object

In [6]:
df['claim_code_description']

0                GP CONSULTATION
1                GP CONSULTATION
2                    NIL PAYMENT
3                GP CONSULTATION
4                    NIL PAYMENT
                   ...
634782    OTC MEDICATION BENEFIT
634783          CHRONIC MEDICINE
634784          CHRONIC MEDICINE
634785    OTC MEDICATION BENEFIT
634786          CHRONIC MEDICINE
Name: claim_code_description, Length: 634787, dtype: object

In [7]:
df['icd10_descr']

0                                                  Headache
1                               Zoster without complication
2                                                    Myopia
3            Acute upper respiratory infection, unspecified
4                            Atopic dermatitis, unspecified
                                ...
634782    Persons encountering health services in unspec...
634783    Persons encountering health services in unspec...
634784    Persons encountering health services in unspec...
634785    Persons encountering health services in unspec...
634786    Persons encountering health services in unspec...
Name: icd10_descr, Length: 634787, dtype: object

In [9]:
set(df['in_hospital_indicator'])

{'N', 'Y'}

In [11]:

len(set(df['auth_fk']))

63190

In [12]:
df[['claim_type',
 'claim_code',
 'claim_code_description',
 'icd10_fk',
 'icd10_descr',
 'icd10_group_description']]

,claim_type,claim_code,claim_code_description,icd10_fk,icd10_descr,icd10_group_description
0,C,14,GP CONSULTATION,R51,Headache,Headache
1,C,14,GP CONSULTATION,B02.9,Zoster without complication,Zoster [herpes zoster]
2,C,99,NIL PAYMENT,H52.1,Myopia,Disorders of refraction and accommodation
3,C,14,GP CONSULTATION,J06.9,"Acute upper respiratory infection, unspecified",Acute upper respiratory infections of multiple...
4,C,99,NIL PAYMENT,L20.9,"Atopic dermatitis, unspecified",Atopic dermatitis
...,...,...,...,...,...,...
634782,C,74,OTC MEDICATION BENEFIT,Z76.9,Persons encountering health services in unspec...,Persons encountering health services in other ...
634783,P,61,CHRONIC MEDICINE,Z76.9,Persons encountering health services in unspec...,Persons encountering health services in other ...
634784,P,61,CHRONIC MEDICINE,Z76.9,Persons encountering health services in unspec...,Persons encountering health services in other ...
634785,C,74,OTC MEDICATION BENEFIT,Z76.9,Persons encountering health services in unspec...,Persons encountering health services in other ...
634786,P,61,CHRONIC MEDICINE,Z76.9,Persons encountering health services in unspec...,Persons encountering health services in other ...

In [29]:
set(df['claim_type'])

{'A', 'C', 'K', 'P', 'k'}

In [18]:
df[df['claim_type']=='A'][['claim_type',
 'claim_code',
 'claim_code_description',
 'icd10_fk',
 'icd10_descr',
 'icd10_group_description']]

,claim_type,claim_code,claim_code_description,icd10_fk,icd10_descr,icd10_group_description
3433,A,141,IN PATIENT PRIVATE HOSPITAL,G40.9,"Epilepsy, unspecified",Epilepsy
3435,A,141,IN PATIENT PRIVATE HOSPITAL,G40.9,"Epilepsy, unspecified",Epilepsy
3602,A,141,IN PATIENT PRIVATE HOSPITAL,G40.9,"Epilepsy, unspecified",Epilepsy
158686,A,141,IN PATIENT PRIVATE HOSPITAL,Z91.5,Personal history of self-harm,"Personal history of risk-factors, not elsewher..."
158689,A,141,IN PATIENT PRIVATE HOSPITAL,Z91.5,Personal history of self-harm,"Personal history of risk-factors, not elsewher..."
213422,A,140,OUTPATIENT TRAUMA WARD,S43.7,Sprain and strain of other and unspecified par...,"Dislocation, sprain and strain of joints and l..."
213423,A,140,OUTPATIENT TRAUMA WARD,S43.7,Sprain and strain of other and unspecified par...,"Dislocation, sprain and strain of joints and l..."
540751,A,85,AMBULANCE,S40.0,Contusion of shoulder and upper arm,Superficial injury of shoulder and upper arm
540754,A,85,AMBULANCE,S40.0,Contusion of shoulder and upper arm,Superficial injury of shoulder and upper arm

In [31]:
set(df['icd10_fk'])

{nan,
 'G21.9',
 'K80.8',
 'S61.7',
 'Z72.5',
 'G55.0',
 'M40.56',
 'M46.18',
 'H81.3',
 'L81.4',
 'U98.0',
 'F31.1',
 'G24.9',
 'R09.2',
 'M60.84',
 'E20.9',
 'N12',
 'Z76.1',
 'M62.98',
 'M23.30',
 'H73.0',
 'O86.0',
 'C47.5',
 'F14.9',
 'M72.39',
 'K62.9',
 'N92.4',
 'L29.9',
 'E13.9',
 'Z76.9',
 'R07.4',
 'M50.9',
 'T09.0',
 'Z11.6',
 'J20.1',
 'L27.8',
 'Q21.9',
 'M60.85',
 'E78.0',
 'M85.99',
 'E78.2',
 'F41.2',
 'N83.2',
 'M77.37',
 'H35.5',
 'M79.04',
 'L05.0',
 'C50.9',
 'K27.1',
 'B35.4',
 'M10.09',
 'L21.9',
 'I95.0',
 'O33.2',
 'L65.8',
 'S33.7',
 'Z10.0',
 'K59.1',
 'H33.4',
 'J39.8',
 'H53.2',
 'S02.50',
 'T78.9',
 'M79.7',
 'M47.82',
 'F17.2',
 'Z29.0',
 'Q63.8',
 'M19.95',
 'M41.34',
 'M99.81',
 'Z40.9',
 'S60.1',
 'G47.8',
 'K09.0',
 'G21.2',
 'W44.52',
 'I46.9',
 'N93.8',
 'X12.9',
 'Z01.7',
 'O32.1',
 'Z02.7',
 'F81.9',
 'L98.0',
 'L10.2',
 'Z95.4',
 'S90.9',
 'M54.13',
 'Z08.9',
 'K72.9',
 'F31.9',
 'G40.3',
 'S50.9',
 'Z97.3',
 'M25.61',
 'W19.99',
 'K92.9',
 'E11.2',
 'J10',
 'O22.0',
 'F48.9',
 'J40',
 'S00.9',
 'M15.0',
 'K60.5',
 'P22.9',
 'A03.9',
 'O42.9',
 'K41.1',
 'R41.3',
 'I86.8',
 'M25.90',
 'Z60.8',
 'Z88.9',
 'M60.19',
 'A09.0',
 'N32.9',
 'K25.0',
 'M79.20',
 'M81.99',
 'M33.2',
 'M54.17',
 'M43.08',
 'J30.2',
 'A64',
 'M13.96',
 'S22.40',
 'S01.2',
 'E14.9',
 'B81.2',
 'R15',
 'B43.2',
 'M24.46',
 'N97.8',
 'R93.6',
 'M15.4',
 'H51.0',
 'S44.8',
 'M41.9',
 'L89.9',
 'J11',
 'L04.0',
 'O82.1',
 'L70.8',
 'M41.24',
 'G62.9',
 'M02.98',
 'S20.8',
 'K11.2',
 'M17.0',
 'L30.9',
 'N03.2',
 'I60.9',
 'O12.1',
 'Z33',
 'G25.9',
 'O23.5',
 'L70.1',
 'G40.5',
 'T88.7',
 'I51.9',
 'Z03.1',
 'J80',
 'R19.3',
 'H16.9',
 'O03.5',
 'S83.0',
 'G56.0',
 'Z46.9',
 'R58',
 'K64.8',
 'N11.9',
 'N18.4',
 'B33.8',
 'S98.3',
 'M47.95',
 'J33.1',
 'K28.9',
 'K42.0',
 'I49.8',
 'H52',
 'H91.2',
 'Z59.4',
 'M00.99',
 'S29.9',
 'N94.5',
 'K60.2',
 'M45.X2',
 'K26.9',
 'N94.3',
 'R79.0',
 'G51.9',
 'K11.3',
 'J67.9',
 'T10.X0',
 'N83.0',
 'S82.90',
 'D20.1',
 'A49.2',
 'M13.87',
 'M79.69',
 'S82.31',
 'M19.19',
 'M08.09',
 'M94.0',
 'J69.8',
 'N70.0',
 'H81.1',
 'J20.9',
 'F51.9',
 'N80.2',
 'B17.9',
 'M60.08',
 'K02.1',
 'J98.4',
 'B87.1',
 'K64.4',
 'M70.81',
 'S50.8',
 'D73.9',
 'B08.8',
 'R05',
 'H68.1',
 'Z30.1',
 'M35.3',
 'M10.97',
 'M21.50',
 'Q66.8',
 'G24.3',
 'N30.4',
 'R60.0',
 'Z88.1',
 'L25.9',
 'Q43.2',
 'M25.05',
 'M54.00',
 'Q78.5',
 'B50.9',
 'Z30.3',
 'M23.89',
 'S62.30',
 'T25.1',
 'F06.3',
 'S96.0',
 'K63.9',
 'L03.9',
 'P39.0',
 'M60.00',
 'M67.8',
 'M65.18',
 'S63.1',
 'S39.9',
 'J35.8',
 'M23.83',
 'S54.2',
 'K80.2',
 'S89.9',
 'M67.4',
 'I47.2',
 'S92.30',
 'M62.09',
 'M06.21',
 'J01.0',
 'F34.8',
 'E83.1',
 'N50.8',
 'T67.1',
 'D64.9',
 'M54.21',
 'Z53.2',
 'M79.01',
 'M71.02',
 'C34.9',
 'H66.0',
 'M54.98',
 'O14.9',
 'S64.9',
 'A85.2',
 'R03.0',
 'S90.3',
 'G25.0',
 'D53.8',
 'Z70.9',
 'A63.8',
 'M05.99',
 'H05.0',
 'R43.0',
 'R22.1',
 'F31.3',
 'N94.4',
 'B86',
 'K56.4',
 'O21.0',
 'M23.94',
 'A58',
 'F19.0',
 'B20.3',
 'M77.02',
 'N23',
 'L29.1',
 'S52.50',
 'N81.3',
 'H92.0',
 'T63.4',
 'C39.0',
 'S62.60',
 'M15.9',
 'M92.9',
 'Z86.4',
 'J32.8',
 'E87.6',
 'N50.9',
 'D17.0',
 'G30.0',
 'B83',
 'S57.0',
 'I95.9',
 'G90.9',
 'M41.86',
 'M47.81',
 'G50.9',
 'R43.8',
 'J66.8',
 'S46.9',
 'K27.6',
 'S09.7',
 'C43.5',
 'M13.14',
 'M47.90',
 'M25.69',
 'T02.10',
 'E14.7',
 'R94.6',
 'R94.3',
 'J18.0',
 'H11.1',
 'K02.0',
 'J20.5',
 'Z25.1',
 'R81',
 'S52.6',
 'M54.55',
 'M25.40',
 'N81.2',
 'Z70.1',
 'Y34.99',
 'S93.6',
 'M00.80',
 'M12.81',
 'K81.0',
 'B36.9',
 'S20.3',
 'H10.3',
 'E88.2',
 'A50.9',
 'M17.5',
 'M25.59',
 'S05.8',
 'M71.07',
 'M79.94',
 'S00.0',
 'M75.3',
 'M62.45',
 'M67.9',
 'M47.86',
 'N30.1',
 'K29.6',
 'M79.08',
 'B26.0',
 'Z09.4',
 'M24.59',
 'K08.9',
 'M79.95',
 'S62.50',
 '99999',
 'H90.8',
 'J05.0',
 'Z11.5',
 'E83.4',
 'K13.7',
 'A03.8',
 'O46.9',
 'L03.0',
 'B48.1',
 'M19.17',
 'H18.8',
 'L40.5',
 'M60.10',
 'N94.8',
 'A09',
 'M45.X9',
 'F45.3',
 'H72.0',
 'Z13.2',
 'K06.0',
 'A16.1',
 'L73.8',
 'Z98.1',
 'B19.9',
 'S82.11',
 'D25.2',
 'F90.0',
 'J70.9',
 'M79.93',
 'J35.9',
 'D22.9',
 'K90.4',
 'M65.29',
 'B83.8',
 'E34.9',
 'M05.15',
 'N75.9',
 'R61.9',
 'C43.4',
 'R70.0',
 'R73.9',
 'S69.7',
 'A87.9',
 'L27.9',
 'M54.46',
 'M65.93',
 'M00.96',
 'I78.1',
 'J34.0',
 'F98.8',
 'N30.8',
 'S82.00',
 'M93.8',
 'U07',
 'R20.2',
 'M77.4',
 'K83.9',
 'A53.0',
 'U07.22',
 'A04.9',
 'O00.0',
 'R25.2',
 'M94.89',
 'D46.9',
 'D53.9',
 'P74.1',
 'M41.26',
 'B66.8',
 'R87.9',
 'Z51.9',
 'M79.05',
 'S52.60',
 'H68.0',
 'S93.0',
 'S03.5',
 'T74.2',
 'Q63.2',
 'L60.8',
 'H52.3',
 'J31.2',
 'S0.00',
 'K36',
 'C03.9',
 'E88.8',
 'M54.6',
 'N92.0',
 'M13.17',
 'M23.40',
 'N99.4',
 'L01.0',
 'H11.3',
 'C46.0',
 'B01.8',
 'B46.2',
 'J39.2',
 'L81.6',
 'L65.9',
 'I27.0',
 'G45.9',
 'N88.0',
 'I50.1',
 'M62.99',
 'N91.0',
 'D22.5',
 'M53.03',
 'J21.8',
 'S60.8',
 'S81.7',
 'N39.4',
 'S02.30',
 'S00.8',
 'M48.49',
 'H90.3',
 'O60.0',
 'S67.0',
 'F52.0',
 'C09.9',
 'Z75.0',
 'G47.1',
 'R29.4',
 'E61.1',
 '099',
 'T14.5',
 'F43.1',
 'H81.9',
 'M62.90',
 'M54.14',
 'H66.4',
 'B18.9',
 'M10.27',
 'K63.3',
 'R13',
 'Z32.0',
 'N45.0',
 'H93.1',
 'E84.8',
 'N13.6',
 'M10.98',
 'B35.3',
 'R10.3',
 'M77.24',
 'M62.60',
 'Q53.1',
 'T30.1',
 'M62.95',
 'N85.9',
 'M54.37',
 'M43.63',
 'S70.0',
 'M25.41',
 'M65.01',
 'J15.9',
 'T14.8',
 'R06.0',
 'M54.15',
 'T13.9',
 'M06.02',
 'O06.8',
 'X11.99',
 'L59.0',
 'O23.4',
 'I83.1',
 'M47.20',
 'D29.1',
 'J38.7',
 'L50.1',
 'M23.23',
 'M06.9',
 'M76.56',
 'M54.87',
 'M79.98',
 'K52.3',
 'R29.8',
 'J95.8',
 'S76.4',
 'Z71.9',
 'K64.2',
 'M79.02',
 'M10.96',
 'Z73.3',
 'N41.9',
 'Z04.1',
 'S50.1',
 'D46.4',
 'M71.90',
 'K80.1',
 'N26',
 'S81.9',
 'M05.24',
 'M13.94',
 'E14.8',
 'S52.30',
 'B83.9',
 'O62.2',
 'K09.8',
 'N70.1',
 'I80.3',
 'F03',
 'S39.7',
 'M79.88',
 'M12.88',
 'M62.50',
 'M47.80',
 'Z29.1',
 'I26.0',
 'L72.0',
 'D23.6',
 'B30.2',
 'B39.5',
 'Z01.6',
 'G47.2',
 'S63.7',
 'M54.69',
 'M79.91',
 'N85.8',
 'Z36.3',
 'M51.1',
 'Z47.9',
 'H05.2',
 'E51.9',
 'K46.1',
 'O06.9',
 'K26.5',
 'L02.4',
 'B77.0',
 'M50.0',
 'Q18.9',
 'S10.8',
 'Z97.2',
 'R94.7',
 'M65.94',
 'G11.8',
 'K07.6',
 'T79.3',
 'M70.84',
 'I05.1',
 'O99.0',
 'K04.5',
 'K76.9',
 'E11.3',
 'M67.3',
 'A90',
 'M25.52',
 'M62.15',
 'M54.22',
 'O04.4',
 'J06.8',
 'L30.8',
 'R26.2',
 'O12.0',
 'S42.80',
 'J30.4',
 'M19.05',
 'R11.2',
 'H15.9',
 'M65.09',
 'Z10.2',
 'S62.00',
 'F32.8',
 'J30.1',
 'E55.9',
 'U07L.2',
 'N72',
 'F31.2',
 'Z02.8',
 'S96.1',
 'N76.6',
 'S62.61',
 'R11',
 'C84.0',
 'L02.2',
 'M46.99',
 'F31',
 'R19.6',
 'C53.9',
 'M41.56',
 'A49.0',
 'N92.1',
 'N64.0',
 'B76.9',
 'B46.9',
 'J05.1',
 'B37.7',
 'L56.3',
 'W54.09',
 'O06.3',
 'B07',
 'S82.60',
 'Z72.9',
 'F51.1',
 'N87.2',
 'I09.9',
 'M54.23',
 'K08.0',
 'F31.0',
 'K03.4',
 'G44.2',
 'M77.47',
 'Z13.9',
 'R74.8',
 'F17.9',
 'N87.9',
 'E13.8',
 'O03.1',
 'L64.9',
 'M06.25',
 'Z00.8',
 'I80.8',
 'Z72.6',
 'Z63.4',
 'Z10.1',
 'L40.1',
 'N30.9',
 'S22.30',
 'L03.3',
 'Z36.9',
 'C43.7',
 'H66.2',
 'T40.2',
 'M10.00',
 'L23.0',
 'M13.92',
 'Z73.8',
 'K63.4',
 'M71.05',
 'A49.9',
 'N60.2',
 'L05.9',
 'C31.1',
 'Z26.9',
 'Z74.0',
 'E74.9',
 'R00.0',
 'K01.1',
 'C50.0',
 'M24.21',
 'M54.30',
 'H61.9',
 'O13',
 'R22.7',
 'M25.88',
 'M00.97',
 'H15.0',
 'Z46.7',
 'M25.29',
 'O80.0',
 'S46.8',
 'F41.1',
 'B06.9',
 'L03.1',
 'G20',
 'H70.0',
 'J06.90',
 'M06.89',
 'K27.3',
 'Z83.6',
 'R32',
 'M43.02',
 'T67.0',
 'M54.4',
 'H53.9',
 'T43.2',
 'J20.6',
 'K27',
 'M41.99',
 'O23.9',
 'H35.3',
 'F60.9',
 'T50.0',
 'H60.0',
 'C06.2',
 'I25.1',
 'N91.4',
 'J37.0',
 'V36.02',
 'K92.2',
 'B97.7',
 'N64.8',
 'A51.0',
 'J18.1',
 'B23.8',
 'S82.40',
 'H26.1',
 'A06.9',
 'I20.9',
 'H00.1',
 'M72.27',
 'S69.9',
 'E15',
 'R40.0',
 'M75.8',
 'J01.3',
 'E10.5',
 'F50.9',
 'S01.4',
 'M05.90',
 'J02.9',
 'N93.9',
 'M70.56',
 'T21.4',
 'A16.7',
 'T78.4',
 'T14.0',
 'M25.76',
 'N41.8',
 'B88.0',
 'M47.26',
 'H93.0',
 'B20.8',
 'H65.1',
 'F98.9',
 'F10.1',
 'F43.0',
 'S05.9',
 'E56.9',
 'H71',
 'M65.02',
 'L98.8',
 'M97.18',
 'M43.60',
 'M95.1',
 'M06.98',
 'N73.8',
 'M47.10',
 'M06.91',
 'M61.00',
 'S06.60',
 'B00.2',
 'M25.9',
 'Z30.4',
 'S81.0',
 'D23.2',
 'T28.0',
 'O33.5',
 'Z01',
 'M79.1',
 'L25.2',
 'Z38.0',
 'B35.2',
 'M54.29',
 'M13.80',
 'Z36.4',
 'M06.41',
 'J98.2',
 'M65.08',
 'R93.0',
 'M47.97',
 'M61.40',
 'A00.0',
 'N44',
 'F50.5',
 'K29.7',
 'M54.10',
 'I71.4',
 'H57.9',
 'S52.8',
 'M54.09',
 'N63',
 'M43.09',
 'Z82.6',
 'S96.2',
 'K43.2',
 'E03.9',
 'O34.5',
 'M47.83',
 'M23.99',
 'M93.0',
 'K60.1',
 'Y10.99',
 'M79.62',
 'Z10.8',
 'R93.3',
 'K59.9',
 'Z76.8',
 'M05.80',
 'R07.1',
 'M13.89',
 'H90.2',
 'N96',
 'K80.0',
 'F52.3',
 'I20.8',
 'D21.9',
 'D69.9',
 'J46',
 'N19',
 'L21.0',
 'K64.5',
 'M25.11',
 'M89.46',
 'D50.8',
 'S66.7',
 'Z31.3',
 'Z00.4',
 'R16.2',
 'I88.1',
 'M79.63',
 'Z76.3',
 'N64.4',
 'Q23.1',
 'A03.0',
 'Z36.8',
 'R68.1',
 'T49.2',
 'R03.1',
 'R49.0',
 'H02.8',
 'N34.0',
 'I05.9',
 'A68.1',
 'M79.97',
 'I83.2',
 'M54.48',
 'L70.0',
 'J04.1',
 'M25.58',
 'L68.0',
 'O23.1',
 'H57.8',
 'Z39.0',
 'G40.7',
 'S51.9',
 'N93.0',
 'Z35.6',
 'B35.0',
 'R22.3',
 'S53.4',
 'C46.9',
 'C16.0',
 'M89.92',
 'L98.4',
 'M79.74',
 'S60.7',
 'F32.2',
 'F66.2',
 'F01.9',
 'Q66.5',
 'M79.73',
 'M40.22',
 'O94',
 'M19.91',
 'M62.69',
 'H01.1',
 'E07.0',
 'F32.0',
 'M00.04',
 'M81.21',
 'N91.5',
 'L02.3',
 'S54.9',
 'D48.6',
 'S48.0',
 'K29.1',
 'M77.97',
 'J45.0',
 'M62.49',
 'K61.2',
 'M70.98',
 'B37.9',
 'A66.5',
 'M79.23',
 'M48.42',
 'A04.0',
 'N32.8',
 'S31.3',
 'M70.65',
 'H91.9',
 'M91.95',
 'Z04.0',
 'L57.0',
 'M94.26',
 'J21.9',
 'Q76.5',
 'S82.20',
 'S97.8',
 'M65.27',
 'E61.9',
 'S52.41',
 'K11.9',
 'F30.9',
 'N42.1',
 'N73.9',
 'B68.9',
 'S32.20',
 'M61.30',
 'M65.91',
 'M47.89',
 'L73.0',
 'M79.99',
 'S99.9',
 'M40.34',
 'N64.9',
 'K52.0',
 'O91.0',
 'G54.1',
 'R82.7',
 'N90.9',
 'N76.8',
 'M19.01',
 'J11.0',
 'N76.0',
 'M47.99',
 'E10.9',
 'S39.8',
 'R01.0',
 'J39.9',
 'R63.5',
 'D55.9',
 'N41.3',
 'B37.0',
 'M32.9',
 'O04.9',
 'A08.1',
 'M77.81',
 'M77.89',
 'M19.09',
 'F11.2',
 'S32.90',
 'L56.9',
 'M94.10',
 'B15.9',
 'R19.8',
 'S43.4',
 'Z46.8',
 ...}

In [34]:
icd10_fk_df=df[~df['icd10_fk'].isna()]

In [37]:
path="""C:\\Users\\christo.strydom\\AppData\\Local\\Neo4j\\Relate\\Data\\dbmss\\dbms-dfc91feb-eeb1-4c1c-bb5b-c3a01a117a31\\import\\"""

In [38]:
icd10_fk_df.to_csv(path+'icd10_fk_df.csv', index=False)

In [40]:
icd10_fk_df.icd10_fk

0           R51
1         B02.9
2         H52.1
3         J06.9
4         L20.9
          ...
634782    Z76.9
634783    Z76.9
634784    Z76.9
634785    Z76.9
634786    Z76.9
Name: icd10_fk, Length: 634565, dtype: object

In [41]:
icd10_fk_df['ms_fk_id']

0         1491980_00
1          504489_01
2         6013410_00
3          508627_00
4         6022125_02
             ...
634782    1508108_00
634783    1643150_00
634784    1643150_00
634785    1505469_01
634786    1643150_00
Name: ms_fk_id, Length: 634565, dtype: object

In [42]:
set(icd10_fk_df['practice_no'])

{1572865,
 5439493,
 425990,
 327689,
 524298,
 65552,
 6029345,
 32808,
 426024,
 6062121,
 1540157,
 163902,
 1409085,
 589888,
 7700547,
 753734,
 163910,
 524360,
 1572938,
 491594,
 131148,
 1605712,
 65617,
 1474642,
 131164,
 229474,
 1507451,
 32891,
 1409158,
 1409166,
 753815,
 5439647,
 589985,
 884901,
 1507516,
 491713,
 753858,
 884936,
 32972,
 5439698,
 98515,
 655570,
 262358,
 1474774,
 164062,
 524514,
 7012578,
 819433,
 393452,
 393460,
 557307,
 33022,
 5439744,
 622850,
 1507591,
 721166,
 1409298,
 360724,
 1605909,
 229660,
 164127,
 6619428,
 6029620,
 7012667,
 655686,
 360775,
 786764,
 7700814,
 6029647,
 1540440,
 164186,
 1605984,
 5439841,
 557412,
 295272,
 1507699,
 819573,
 1442171,
 262536,
 1409417,
 33170,
 7012756,
 262552,
 1409441,
 5439906,
 197033,
 6029752,
 491969,
 1475010,
 295361,
 1573314,
 1802690,
 3801543,
 1442252,
 786896,
 164305,
 262609,
 459224,
 1606107,
 7012829,
 459232,
 6029795,
 655848,
 655856,
 1573365,
 393738,
 5440017,
 3801624,
 557595,
 197149,
 5440033,
 426547,
 1507893,
 566,
 1475134,
 426563,
 33367,
 1442392,
 5440092,
 459364,
 6029930,
 754285,
 1540718,
 590460,
 230022,
 197262,
 328340,
 393878,
 1475223,
 524964,
 164518,
 7013035,
 819883,
 361135,
 1442481,
 1540785,
 3900088,
 623288,
 393916,
 590525,
 164542,
 1508032,
 99015,
 328405,
 361178,
 787167,
 623334,
 623342,
 1573616,
 164593,
 623350,
 492280,
 1442554,
 7013124,
 819972,
 33545,
 819980,
 295701,
 1540890,
 1442600,
 5440300,
 825,
 7013183,
 6062911,
 557889,
 5440327,
 623431,
 1573705,
 1573713,
 164690,
 263001,
 656224,
 1540963,
 1475428,
 525162,
 623466,
 787310,
 7013264,
 7013272,
 1541021,
 557994,
 6063020,
 394157,
 295868,
 459712,
 656321,
 7013329,
 820180,
 66516,
 132055,
 3802078,
 3802086,
 230383,
 787442,
 230391,
 1410040,
 1475584,
 590851,
 754692,
 459798,
 459801,
 1442848,
 7013418,
 263214,
 7013426,
 66613,
 1573942,
 3802167,
 394297,
 5440580,
 6030416,
 1475673,
 5604443,
 230502,
 558184,
 7013507,
 5440645,
 3802248,
 99465,
 3802256,
 722073,
 6030491,
 361631,
 1574051,
 1442996,
 1508539,
 7013566,
 754897,
 394459,
 1606875,
 394467,
 591076,
 7800037,
 7800045,
 722162,
 197874,
 361720,
 1508601,
 427268,
 6063365,
 427276,
 6063373,
 7013647,
 361747,
 460052,
 918814,
 6063403,
 5440815,
 886068,
 1508660,
 5440823,
 755001,
 427322,
 1410369,
 1475908,
 7013701,
 3802450,
 1607006,
 132454,
 3802485,
 5440890,
 492930,
 198021,
 263567,
 7013779,
 492949,
 689564,
 1574310,
 263591,
 1508776,
 329126,
 787892,
 198072,
 263613,
 689602,
 3802566,
 1410504,
 296392,
 165328,
 3802590,
 5801443,
 263656,
 296430,
 1443321,
 1508857,
 525820,
 820733,
 1410563,
 361992,
 165395,
 755222,
 7013914,
 2000415,
 689696,
 1574434,
 886319,
 1803832,
 558656,
 427586,
 34371,
 624195,
 132675,
 1541706,
 1508946,
 329304,
 329312,
 525928,
 591467,
 1651,
 493171,
 165492,
 591483,
 1607294,
 5441161,
 165514,
 394890,
 1509004,
 394904,
 689831,
 1708,
 7014066,
 1541811,
 722618,
 1724,
 67261,
 591556,
 5441226,
 1476300,
 1607383,
 7014104,
 67288,
 6063837,
 558826,
 657131,
 1607405,
 689904,
 7014139,
 100110,
 1509136,
 34576,
 2000660,
 755478,
 591653,
 526118,
 1574698,
 6620973,
 755516,
 34622,
 1541951,
 132934,
 1607499,
 1410903,
 100196,
 722790,
 526185,
 1443690,
 1509225,
 5441390,
 1509233,
 7014260,
 460664,
 7210876,
 6064000,
 3803023,
 657298,
 264083,
 329622,
 5441439,
 788384,
 886688,
 1443747,
 6064043,
 1509292,
 427950,
 1574833,
 1542087,
 427977,
 6064086,
 165859,
 67555,
 133094,
 329703,
 2000873,
 3803120,
 788473,
 2046,
 5801982,
 100358,
 657417,
 329738,
 7014414,
 1804316,
 1542176,
 657441,
 1542192,
 100404,
 559164,
 788546,
 264261,
 1443917,
 886866,
 1443925,
 395358,
 2143,
 526436,
 3803244,
 723053,
 297070,
 100463,
 395374,
 1509489,
 821365,
 67709,
 591998,
 428159,
 5441668,
 2186,
 592013,
 1476750,
 3803279,
 1411225,
 1575066,
 755869,
 264350,
 1509535,
 7014562,
 493740,
 6031544,
 3803325,
 395455,
 2240,
 166081,
 1542338,
 755907,
 231622,
 755915,
 395471,
 100560,
 690392,
 1607898,
 1444069,
 690406,
 395498,
 5441773,
 7014643,
 1607936,
 657670,
 5441811,
 3803414,
 723223,
 2001179,
 1542435,
 690473,
 428329,
 2001195,
 493880,
 67911,
 3803465,
 723274,
 1444182,
 1542486,
 297305,
 592218,
 756059,
 1804634,
 35165,
 6031706,
 461148,
 821608,
 395625,
 5441897,
 395633,
 133493,
 526711,
 756091,
 1804669,
 6031749,
 166278,
 6064523,
 428434,
 133523,
 526746,
 133531,
 297372,
 657824,
 2001314,
 7014821,
 6031781,
 428469,
 297402,
 1804731,
 428477,
 428485,
 264652,
 1444301,
 6031838,
 166367,
 5802466,
 199141,
 1608177,
 494070,
 1608185,
 2001411,
 756229,
 756237,
 559636,
 264725,
 756245,
 690708,
 1608215,
 100889,
 2585,
 592412,
 5442079,
 133663,
 559652,
 231975,
 7014953,
 5442095,
 1575481,
 461369,
 5442109,
 5802563,
 3803724,
 789070,
 100943,
 264784,
 1542737,
 297550,
 1411667,
 3803732,
 35424,
 1509985,
 166502,
 2666,
 6031978,
 428663,
 7015054,
 789135,
 494224,
 166545,
 166553,
 35483,
 166561,
 1608355,
 5442214,
 756393,
 527017,
 1575597,
 690864,
 1575600,
 658111,
 494275,
 166596,
 428744,
 1608401,
 494291,
 658138,
 35548,
 821993,
 5442281,
 6064876,
 297712,
 690937,
 1411837,
 690953,
 199435,
 690961,
 6064914,
 527130,
 35610,
 396060,
 461601,
 166693,
 3803945,
 461628,
 1444670,
 1608517,
 822094,
 68438,
 396125,
 6032222,
 68454,
 428906,
 1543024,
 199540,
 166774,
 723835,
 232319,
 5802881,
 428930,
 199559,
 5442443,
 461709,
 7015313,
 101265,
 166804,
 658324,
 68519,
 134058,
 428973,
 1543091,
 396214,
 232378,
 297917,
 134082,
 1510355,
 527319,
 3804119,
 1477595,
 68586,
 461806,
 3804143,
 396273,
 166898,
 723967,
 68608,
 297984,
 297992,
 363529,
 232459,
 134155,
 7015445,
 101397,
 723991,
 822299,
 1608738,
 1805355,
 461873,
 298042,
 101435,
 560189,
 7015488,
 4000838,
 822345,
 1477714,
 298077,
 1608797,
 1608800,
 3804259,
 232556,
 199788,
 101486,
 756849,
 658545,
 724084,
 625787,
 756865,
 5442699,
 396427,
 199826,
 1608851,
 1543326,
 1805479,
 691372,
 1543342,
 494771,
 1445049,
 232637,
 396478,
 3804356,
 232645,
 134341,
 5442761,
 3804372,
 625884,
 298204,
 1543393,
 199907,
 3301,
 429287,
 199915,
 1608940,
 494828,
 68845,
 363758,
 68853,
 1805568,
 1510657,
 167185,
 5442834,
 1445146,
 363804,
 36145,
 167223,
 7015739,
 3387,
 396605,
 920894,
 757055,
 167231,
 1445189,
 1445197,
 5803349,
 757098,
 265578,
 1478001,
 658804,
 36226,
 1412485,
 822663,
 462225,
 363928,
 6065562,
 69019,
 7015836,
 3484,
 1445286,
 5442982,
 527785,
 822701,
 691631,
 1609149,
 1445316,
 101834,
 658901,
 822744,
 265691,
 331236,
 495077,
 691690,
 658928,
 5443059,
 265721,
 331260,
 7015933,
 1445375,
 1445383,
 1543687,
 3804690,
 1805843,
 495131,
 167452,
 691739,
 200220,
 7540256,
 1543717,
 7015976,
 691755,
 462381,
 560685,
 1510959,
 691763,
 36412,
 7212607,
 2100800,
 6065732,
 134724,
 396869,
 560715,
 527947,
 396877,
 331341,
 3662,
 1609297,
 3804755,
 560731,
 1805916,
 593516,
 134775,
 167568,
 822930,
 7016085,
 2100886,
 134805,
 298646,
 1412760,
 1805975,
 7016093,
 298654,
 3743,
 6033059,
 1576615,
 691879,
 1511084,
 7016115,
 364215,
 6000312,
 1445561,
 1478338,
 6065872,
 921300,
 7016158,
 3804917,
 7016182,
 3832,
 5443326,
 134910,
 1609491,
 69396,
 233242,
 724769,
 331554,
 233250,
 757543,
 724777,
 298794,
 1478443,
 1478451,
 266035,
 102199,
 200506,
 528188,
 7016255,
 200514,
 462659,
 1511246,
 298832,
 1412949,
 1412957,
 3805034,
 331635,
 298867,
 1511289,
 1478532,
 921505,
 167843,
 36773,
 790443,
 266159,
 757691,
 7016395,
 757713,
 5443539,
 1576917,
 5443547,
 1478621,
 1445855,
 7016417,
 1511394,
 7016425,
 364525,
 430064,
 397296,
 593907,
 1478648,
 593915,
 757756,
 1511432,
 725005,
 331791,
 1576976,
 200727,
 495646,
 790559,
 6066208,
 1413155,
 36900,
 823333,
 790567,
 757802,
 725048,
 135224,
 659517,
 1609793,
 725080,
 4200,
 1806440,
 200808,
 364657,
 1577077,
 69752,
 266361,
 1413244,
 692352,
 6066305,
 1478788,
 725129,
 594059,
 1511564,
 659606,
 3805336,
 659622,
 430250,
 102571,
 1544373,
 1478842,
 561339,
 135356,
 168130,
 528579,
 495816,
 594121,
 69841,
 528595,
 1544403,
 1478869,
 626902,
 430307,
 37095,
 757993,
 430315,
 266477,
 692468,
 364797,
 758019,
 790796,
 1609998,
 692514,
 1610023,
 4391,
 561452,
 1413422,
 6066488,
 135488,
 1478982,
 7016778,
 168270,
 7016786,
 397652,
 69973,
 102741,
 463205,
 364908,
 3805549,
 6066550,
 397687,
 1479032,
 70009,
 594296,
 1610112,
 364932,
 4502,
 201111,
 135577,
 37273,
 1479067,
 5443997,
 692638,
 1544608,
 7016867,
 233900,
 266671,
 201138,
 6066623,
 1511874,
 725447,
 430544,
 37338,
 725498,
 823805,
 1544713,
 70157,
 6066712,
 102938,
 1446428,
 528927,
 1479202,
 7016999,
 102954,
 430641,
 397873,
 660019,
 528951,
 692816,
 1512021,
 6001246,
 3805794,
 5444195,
 692840,
 5804655,
 6066801,
 7017073,
 725625,
 430714,
 7017081,
 561789,
 430722,
 6066828,
 660108,
 758418,
 266906,
 561819,
 1479326,
 791202,
 266914,
 397989,
 6066860,
 7017138,
 6034101,
 234168,
 299707,
 5444284,
 365254,
 1512137,
 168653,
 660175,
 692948,
 1446614,
 561878,
 561886,
 332518,
 1807080,
 1479407,
 201456,
 332534,
 496375,
 1446649,
 3805948,
 5444349,
 ...}

In [47]:
df[['claim_type',
 'claim_code',
 'claim_code_description']]

       claim_type  claim_code  claim_code_description
0               C          14         GP CONSULTATION
1               C          14         GP CONSULTATION
2               C          99             NIL PAYMENT
3               C          14         GP CONSULTATION
4               C          99             NIL PAYMENT
...           ...         ...                     ...
634782          C          74  OTC MEDICATION BENEFIT
634783          P          61        CHRONIC MEDICINE
634784          P          61        CHRONIC MEDICINE
634785          C          74  OTC MEDICATION BENEFIT
634786          P          61        CHRONIC MEDICINE

[634787 rows x 3 columns]